---
cloud_service_group: ECS
cloud_service_type: Cluster
name: Running Tasks by Cluster
query:
  aggregate:
    - unwind:
        path: data.tasks
    - group:
        keys:
        - name: name
          key: name
        fields:
        - name: value
          key: data.tasks
          operator: count
    - sort:
        key: value
        desc: true
options:
  chart_type: COLUMN
