---
cloud_service_group: ECS
cloud_service_type: Cluster
name: Running Task Total Count
query:
  aggregate:
    - unwind:
        path: data.tasks
    - group:
        fields:
        - name: value
          key: data.tasks
          operator: count
options:
  value_options:
    key: value
    options:
      default: 0