---
cloud_service_group: Lightsail
cloud_service_type: Bucket
name: Object Total Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.object_count
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0