---
cloud_service_group: Lightsail
cloud_service_type: Disk
name: Total Size by Availability Zone
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.location.availability_zone
        fields:
          - name: value
            key: instance_size
            operator: sum
options:
  chart_type: COLUMN
  value_options:
    key: value
    type: size
    options:
      source_unit: GB
      default: 0