---
cloud_service_group: Lightsail
cloud_service_type: Disk
name: Total Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: instance_size
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      source_unit: GB
      default: 0
