---
cloud_service_group: Lightsail
cloud_service_type: Database
name: Total Memory Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.hardware.ram_size_in_gb
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      source_unit: GB
      default: 0