---
cloud_service_group: Lightsail
cloud_service_type: Database
name: Total CPU Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.hardware.cpu_count
            operator: sum
options:
  value_options:
    key: value
    options:
      default: 0
