---
cloud_service_group: Lightsail
cloud_service_type: Database
name: Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            operator: data.hardware.disk_size_in_gb
options:
  value_options:
    key: value
    type: size
    options:
      source_unit: GB
      default: 0
