---
cloud_service_group: EC2
cloud_service_type: AutoScalingGroup
name: Count by Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
