---
cloud_service_group: EC2
cloud_service_type: AutoScalingGroup
name: Releated ELB Total Count
query:
  aggregate:
    - unwind:
        path: data.load_balancers
    - group:
        fields:
          - name: value
            key: data.load_balancers
            operator: count
options:
  value_options:
    key: value
    options:
      default: 0