---
cloud_service_group: EC2
cloud_service_type: AutoScalingGroup
name: Related Instance Total Count
query:
  aggregate:
    - unwind:
        path: data.instances
    - group:
        fields:
          - name: value
            key: data.instances
            operator: count
