---
cloud_service_group: SNS
cloud_service_type: Topic
name: Subscription Cout by Account
query:
  aggregate:
    - unwind:
        path: data.subscriptions
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: data.subscriptions
            operator: count
options:
  chart_type: DONUT
