---
cloud_service_group: SNS
cloud_service_type: Topic
name: Topic per Account
query:
  aggregate:
    - group:
        keys:
          - name: account
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
