---
cloud_service_group: SQS
cloud_service_type: Queue
name: Queue Maximum Message Total Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.maximum_message_size
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0