---
cloud_service_group: EC2
cloud_service_type: Snapshot
name: Snapshot Total Count per Account
query:
  aggregate:
    - group:
        keys:
          - name: account
            key: account
        fields:
          - name: count
            operator: count
options:
  chart_type: DONUT