---
cloud_service_group: EC2
cloud_service_type: Volume
name: Total Size by State
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.state
        fields:
          - name: value
            key: instance_size
            operator: sum
options:
  chart_type: TREEMAP
  value_options:
    key: value
    type: size
