---
cloud_service_group: EC2
cloud_service_type: Volume
name: Total Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: instance_size
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
