---
cloud_service_group: KinesisFirehose
cloud_service_type: DeliveryStream
name: Delivery Stream per Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            operator: count
options:
  chart_type: COLUMN
