---
cloud_service_group: Lambda
cloud_service_type: Function
name: Code Total Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: instance_size
            operator: sum
options:
  value_options:
    key: value
    type: size
