---
cloud_service_group: Lambda
cloud_service_type: Function
name: Lambda Code Total Size
query:
  aggregate:
    - group:
        fields:
          - name: size
            key: instance_size
            operator: sum
