---
cloud_service_group: DynamoDB
cloud_service_type: Table
name: Read Capacity Total Count
query:
  aggregate:
    - group:
        fields:
          - name: capacity
            operator: sum
            key: data.total_read_capacity
