---
cloud_service_group: DynamoDB
cloud_service_type: Table
name: Storage Total Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            operator: sum
            key: instance_size
options:
  value_options:
    key: value
    type: size