---
cloud_service_group: DynamoDB
cloud_service_type: Table
name: Table Count by Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
