---
cloud_service_group: DynamoDB
cloud_service_type: Table
name: Table Count by Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            operator: count
options:
  chart_type: COLUMN
