---
cloud_service_group: VPC
cloud_service_type: InternetGateway
name: Total Count
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  value_options:
    key: value
    options:
      default: 0