---
cloud_service_group: ECR
cloud_service_type: Repository
name: Image Total Size
query:
  aggregate:
    - unwind:
        path: data.images
    - group:
        fields:
        - name: value
          key: data.images.image_size_in_bytes
          operator: sum
options:
  value_options:
    key: value
    type: size
