---
cloud_service_group: ECR
cloud_service_type: Repository
name: Repository by Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
