---
cloud_service_group: Redshift
cloud_service_type: Cluster
name: Node Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.number_of_nodes
            operator: sum
options:
  value_options:
    key: value
    options:
      default: 0