---
cloud_service_group: Redshift
cloud_service_type: Cluster
name: Snapshot Total Count
query:
  aggregate:
    - unwind:
        path: data.snapshots
    - group:
        fields:
          - name: value
            key: data.snapshots
            operator: count
options:
  value_options:
    key: value
    options:
      default: 0