---
cloud_service_group: Redshift
cloud_service_type: Cluster
name: Snapshot Count by Account
query:
  aggregate:
    - unwind:
        path: data.snapshots
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: data.snapshots
            operator: count
options:
  chart_type: DONUT
