---
cloud_service_group: Redshift
cloud_service_type: Cluster
name: Snapshot Total Count
query:
  aggregate:
    - group:
        fields:
          - name: count
            key: data.snapshots
            operator: size
