---
cloud_service_group: RDS
cloud_service_type: Instance
name: Count by Instance Type
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.instance.db_instance_class
        fields:
          - name: value
            operator: count
options:
  chart_type: TREEMAP
