---
cloud_service_group: RDS
cloud_service_type: Instance
name: Instance Storage Total Size
query:
  aggregate:
    - group:
        fields:
          - name: size
            key: data.allocated_storage
            operator: sum
