---
cloud_service_group: RDS
cloud_service_type: Instance
name: Instance per Account
query:
  aggregate:
    - group:
        keys:
          - name: account
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
