---
cloud_service_group: RDS
cloud_service_type: Snapshot
name: Snapshot Total Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.allocated_storage
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      source_unit: GB
      default: 0