---
cloud_service_group: RDS
cloud_service_type: Snapshot
name: Snapshot per Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            operator: count
options:
  chart_type: COLUMN
