---
cloud_service_group: RDS
cloud_service_type: Snapshot
name: Count by Engine
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: instance_type
        fields:
          - name: value
            operator: count
options:
  chart_type: TREEMAP
