---
cloud_service_group: RDS
cloud_service_type: Snapshot
name: Count by Availability Zone
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.availability_zone
        fields:
          - name: value
            operator: count
options:
  chart_type: COLUMN
