---
cloud_service_group: APIGateway
cloud_service_type: API
name: Count by Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            operator: count
options:
  chart_type: COLUMN
