---
cloud_service_group: S3
cloud_service_type: Bucket
name: Bucket Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.object_count
            operator: sum

