---
cloud_service_group: Route53
cloud_service_type: HostedZone
name: Hosted Zone per Account
query:
  aggregate:
    - group:
        keys:
          - name: account
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
