name: "[Push] Build dev with scan"

on:
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
  
      - name: get current date
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          echo "TIME=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: set version with current date
        id: versioning
        run: |
          echo "::set-output name=VERSION::$(cat src/VERSION | cut -c 2-).${{ env.TIME }}"

      - name: Notice when job fails
        if: failure()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,workflow,job
          author_name: Github Action Slack

  image-scan:
    if: github.repository_owner == 'cloudforet-io'
    needs: versioning
    runs-on: ubuntu-latest
    outputs:
      service: ${{ steps.image-scan.outputs.SERVICE }}
    steps:
      - uses: actions/checkout@v2

      - name: get service name
        run: |
          echo "SERVICE=$(echo ${{ github.repository }} | cut -d '/' -f2)" >> $GITHUB_ENV
          echo "::set-output name=SERVICE::${{ env.SERVICE }})"

      - name: Upload docker
        uses: docker/build-push-action@v2
        with:
          path: .
          repository: pyengine/${{ env.SERVICE }}
          push: false
          tags: cache
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: pyengine/${{ env.SERVICE }}:cache
          output-format: table

      - name: Notice when job fails
        if: failure()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,workflow,job
          author_name: Github Action Slack

  docker-push:
    if: github.repository_owner == 'cloudforet-io'
    needs: image-scan
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ jobs.versioning.outputs.version }}
      SERVICE: ${{ jobs.image-scan.outputs.service }}
    steps:
      - uses: actions/checkout@v2

      - name: get service name
        run: |
          echo "SERVICE=$(echo ${{ github.repository }} | cut -d '/' -f2)" >> $GITHUB_ENV

      - name: Upload docker
        uses: docker/build-push-action@v2
        with:
          path: .
          repository: pyengine/${{ env.SERVICE }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Notice when job fails
        if: failure()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,workflow,job
          author_name: Github Action Slack

  notification:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,ref,workflow,job
          author_name: Github Action Slack
