---
cloud_service_group: KMS
cloud_service_type: Key
name: Key per Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            operator: count
options:
  chart_type: COLUMN
